@echo off

IF NOT EXIST ..\include\common              mkdir  	..\include\common
IF NOT EXIST ..\include\bsp                 mkdir  	..\include\bsp
IF NOT EXIST ..\include\bsp\Generated_Code  mkdir  	..\include\bsp\Generated_Code
IF NOT EXIST ..\include\bsp\tss             mkdir 	..\include\bsp\tss

copy ..\..\config\common\maximum_config.h ..\include\common\maximum_config.h /Y
copy ..\..\config\common\small_ram_config.h ..\include\common\small_ram_config.h /Y
copy ..\..\config\common\smallest_config.h ..\include\common\smallest_config.h /Y
copy ..\..\config\common\verif_enabled_config.h ..\include\common\verif_enabled_config.h /Y
copy ..\..\config\user_config.h ..\include\user_config.h /Y
copy ..\..\mqx\source\bsp\bsp.h ..\include\bsp\bsp.h /Y
copy ..\..\mqx\source\bsp\bsp_cm.h ..\include\bsp\bsp_cm.h /Y
copy ..\..\mqx\source\bsp\bsp_rev.h ..\include\bsp\bsp_rev.h /Y
copy ..\..\mqx\source\bsp\fts_base.h ..\include\bsp\.h /Y
copy ..\..\mqx\source\bsp\init_lpm.h ..\include\bsp\init_lpm.h /Y
copy ..\..\mqx\source\bsp\PE_LDD.h ..\include\bsp\Generated_Code\PE_LDD.h /Y
copy ..\..\mqx\source\bsp\TSS_SystemSetup.h ..\include\bsp\TSS_SystemSetup.h /Y
copy ..\..\mqx\source\include\mqx.h ..\include\bsp\mqx.h /Y
copy ..\..\mqx\source\io\adc\adc.h ..\include\bsp\adc.h /Y
copy ..\..\mqx\source\io\adc\adc_conf.h ..\include\bsp\adc_conf.h /Y
copy ..\..\mqx\source\io\adc\kadc\adc_kadc.h ..\include\bsp\adc_kadc.h /Y
copy ..\..\mqx\source\io\adc\kadc\adc_mk60.h ..\include\bsp\adc_mk60.h /Y
copy ..\..\mqx\source\io\can\flexcan\kflexcan.h ..\include\bsp\kflexcan.h /Y
copy ..\..\mqx\source\io\cm\cm.h ..\include\bsp\cm.h /Y
copy ..\..\mqx\source\io\cm\cm_kinetis.h ..\include\bsp\cm_kinetis.h /Y
copy ..\..\mqx\source\io\debug\iodebug.h ..\include\bsp\iodebug.h /Y
copy ..\..\mqx\source\io\dma\dma.h ..\include\bsp\dma.h /Y
copy ..\..\mqx\source\io\dma\edma.h ..\include\bsp\edma.h /Y
copy ..\..\mqx\source\io\enet\enet.h ..\include\bsp\enet.h /Y
copy ..\..\mqx\source\io\enet\enet_rev.h ..\include\bsp\enet_rev.h /Y
copy ..\..\mqx\source\io\enet\enet_wifi.h ..\include\bsp\enet_wifi.h /Y
copy ..\..\mqx\source\io\enet\ethernet.h ..\include\bsp\ethernet.h /Y
copy ..\..\mqx\source\io\enet\macnet\macnet_1588.h ..\include\bsp\macnet_1588.h /Y
copy ..\..\mqx\source\io\enet\macnet\macnet_mk60.h ..\include\bsp\macnet_mk60.h /Y
copy ..\..\mqx\source\io\enet\macnet\macnet_rev.h ..\include\bsp\macnet_rev.h /Y
copy ..\..\mqx\source\io\enet\phy\phy_ksz8041.h ..\include\bsp\phy_ksz8041.h /Y
copy ..\..\mqx\source\io\esdhc\esdhc.h ..\include\bsp\esdhc.h /Y
copy ..\..\mqx\source\io\flashx\flashx.h ..\include\bsp\flashx.h /Y
copy ..\..\mqx\source\io\flashx\freescale\flash_ftfl.h ..\include\bsp\flash_ftfl.h /Y
copy ..\..\mqx\source\io\flashx\freescale\flash_mk60.h ..\include\bsp\flash_mk60.h /Y
copy ..\..\mqx\source\io\gpio\io_gpio.h ..\include\bsp\io_gpio.h /Y
copy ..\..\mqx\source\io\gpio\kgpio\io_gpio_kgpio.h ..\include\bsp\io_gpio_kgpio.h /Y
copy ..\..\mqx\source\io\hmi\btnled.h ..\include\bsp\btnled.h /Y
copy ..\..\mqx\source\io\hmi\derivative.h ..\include\bsp\derivative.h /Y
copy ..\..\mqx\source\io\hmi\hmi_client.h ..\include\bsp\hmi_client.h /Y
copy ..\..\mqx\source\io\hmi\hmi_lwgpio_provider.h ..\include\bsp\hmi_lwgpio_provider.h /Y
copy ..\..\mqx\source\io\hmi\hmi_provider.h ..\include\bsp\hmi_provider.h /Y
copy ..\..\mqx\source\io\hmi\hmi_tss_provider.h ..\include\bsp\hmi_tss_provider.h /Y
copy ..\..\mqx\source\io\hmi\hmi_uids.h ..\include\bsp\hmi_uids.h /Y
copy ..\..\mqx\source\io\hmi\TSS\shared\TSS_API.h ..\include\bsp\tss\TSS_API.h /Y
copy ..\..\mqx\source\io\hmi\TSS\shared\TSS_DataTypes.h ..\include\bsp\tss\TSS_DataTypes.h /Y
copy ..\..\mqx\source\io\hmi\TSS\shared\TSS_GPIO.h ..\include\bsp\tss\TSS_GPIO.h /Y
copy ..\..\mqx\source\io\hmi\TSS\shared\TSS_Sensor.h ..\include\bsp\tss\TSS_Sensor.h /Y
copy ..\..\mqx\source\io\hmi\TSS\shared\TSS_SensorGPIO.h ..\include\bsp\tss\TSS_SensorGPIO.h /Y
copy ..\..\mqx\source\io\hmi\TSS\shared\TSS_SensorTSI.h ..\include\bsp\tss\TSS_SensorTSI.h /Y
copy ..\..\mqx\source\io\hmi\TSS\shared\TSS_SensorTSIL.h ..\include\bsp\tss\TSS_SensorTSIL.h /Y
copy ..\..\mqx\source\io\hmi\TSS\shared\TSS_StatusCodes.h ..\include\bsp\tss\TSS_StatusCodes.h /Y
copy ..\..\mqx\source\io\hmi\TSS\shared\TSS_SystemSetupVal.h ..\include\bsp\tss\TSS_SystemSetupVal.h /Y
copy ..\..\mqx\source\io\hmi\TSS\shared\TSS_Timer.h ..\include\bsp\tss\TSS_Timer.h /Y
copy ..\..\mqx\source\io\hwtimer\hwtimer.h ..\include\bsp\hwtimer.h /Y
copy ..\..\mqx\source\io\hwtimer\hwtimer_pit.h ..\include\bsp\hwtimer_pit.h /Y
copy ..\..\mqx\source\io\hwtimer\hwtimer_systick.h ..\include\bsp\hwtimer_systick.h /Y
copy ..\..\mqx\source\io\i2c\i2c.h ..\include\bsp\i2c.h /Y
copy ..\..\mqx\source\io\i2c\i2c_ki2c.h ..\include\bsp\i2c_ki2c.h /Y
copy ..\..\mqx\source\io\i2s\i2s.h ..\include\bsp\i2s.h /Y
copy ..\..\mqx\source\io\i2s\i2s_audio.h ..\include\bsp\i2s_audio.h /Y
copy ..\..\mqx\source\io\i2s\i2s_ki2s.h ..\include\bsp\i2s_ki2s.h /Y
copy ..\..\mqx\source\io\io_dun\io_dun.h ..\include\bsp\io_dun.h /Y
copy ..\..\mqx\source\io\io_mem\io_mem.h ..\include\bsp\io_mem.h /Y
copy ..\..\mqx\source\io\io_null\io_null.h ..\include\bsp\io_null.h /Y
copy ..\..\mqx\source\io\lpm\lpm.h ..\include\bsp\lpm.h /Y
copy ..\..\mqx\source\io\lpm\lpm_kinetis.h ..\include\bsp\lpm_kinetis.h /Y
copy ..\..\mqx\source\io\lwgpio\lwgpio.h ..\include\bsp\lwgpio.h /Y
copy ..\..\mqx\source\io\lwgpio\lwgpio_kgpio.h ..\include\bsp\lwgpio_kgpio.h /Y
copy ..\..\mqx\source\io\pcb\io_pcb.h ..\include\bsp\io_pcb.h /Y
copy ..\..\mqx\source\io\pcb\mqxa\pcb_mqxa.h ..\include\bsp\pcb_mqxa.h /Y
copy ..\..\mqx\source\io\pcb\mqxa\pcbmqxav.h ..\include\bsp\pcbmqxav.h /Y
copy ..\..\mqx\source\io\pccard\apccard.h ..\include\bsp\apccard.h /Y
copy ..\..\mqx\source\io\pccard\pccardflexbus.h ..\include\bsp\pccardflexbus.h /Y
copy ..\..\mqx\source\io\pcflash\apcflshpr.h ..\include\bsp\apcflshpr.h /Y
copy ..\..\mqx\source\io\pcflash\ata.h ..\include\bsp\ata.h /Y
copy ..\..\mqx\source\io\pcflash\pcflash.h ..\include\bsp\pcflash.h /Y
copy ..\..\mqx\source\io\pipe\io_pipe.h ..\include\bsp\io_pipe.h /Y
copy ..\..\mqx\source\io\rtc\krtc.h ..\include\bsp\krtc.h /Y
copy ..\..\mqx\source\io\rtc\rtc.h ..\include\bsp\rtc.h /Y
copy ..\..\mqx\source\io\sdcard\sdcard.h ..\include\bsp\sdcard.h /Y
copy ..\..\mqx\source\io\sdcard\sdcard_esdhc\sdcard_esdhc.h ..\include\bsp\sdcard_esdhc.h /Y
copy ..\..\mqx\source\io\sdcard\sdcard_spi\sdcard_spi.h ..\include\bsp\sdcard_spi.h /Y
copy ..\..\mqx\source\io\serial\serial.h ..\include\bsp\serial.h /Y
copy ..\..\mqx\source\io\serial\serl_kuart.h ..\include\bsp\serl_kuart.h /Y
copy ..\..\mqx\source\io\spi\spi.h ..\include\bsp\spi.h /Y
copy ..\..\mqx\source\io\spi\spi_dspi.h ..\include\bsp\spi_dspi.h /Y
copy ..\..\mqx\source\io\spi\spi_dspi_common.h ..\include\bsp\spi_dspi_common.h /Y
copy ..\..\mqx\source\io\spi\spi_dspi_dma.h ..\include\bsp\spi_dspi_dma.h /Y
copy ..\..\mqx\source\io\tchres\tchres.h ..\include\bsp\tchres.h /Y
copy ..\..\mqx\source\io\tfs\tfs.h ..\include\bsp\tfs.h /Y
copy ..\..\mqx\source\io\timer\qpit.h ..\include\bsp\qpit.h /Y
copy ..\..\mqx\source\io\timer\timer_lpt.h ..\include\bsp\timer_lpt.h /Y
copy ..\..\mqx\source\io\timer\timer_qpit.h ..\include\bsp\timer_qpit.h /Y
copy ..\..\mqx\source\io\usb\if_dev_ehci.h ..\include\bsp\if_dev_ehci.h /Y
copy ..\..\mqx\source\io\usb\if_dev_khci.h ..\include\bsp\if_dev_khci.h /Y
copy ..\..\mqx\source\io\usb\if_host_ehci.h ..\include\bsp\if_host_ehci.h /Y
copy ..\..\mqx\source\io\usb\if_host_khci.h ..\include\bsp\if_host_khci.h /Y
copy ..\..\mqx\source\io\usb\usb_bsp.h ..\include\bsp\usb_bsp.h /Y
